name: Create Release on Push to MAIN
on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get-latest-tag
        run: |
latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
echo "Latest tag is: $latest_tag"
          next_tag=$(echo $latest_tag | awk -F. -v OFS=. '{$NF++; print}')
          echo "Next tag: $next_tag"
          echo "TAG=$next_tag" >> $GITHUB_ENV

      - name: Create Release and Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: "Release ${{ env.TAG }}"
